config/routes.rb
Rails.application.routes.draw do
  resources :products, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks

end

app/models/form/product_collection.rb
class Form::ProductCollection < Form::Base
  FORM_COUNT = 5 #ここで、作成したい登録フォームの数を指定
  attr_accessor :products #fields_for 第一引数に渡す変数にアクセスできる必要があるためこの記述が必要

  def initialize(attributes = {})
    super attributes # initializeの中でsuper attributesとしてますがそれが呼ばれる結果products_attributes=(attributes)も呼ばれます。
    self.products = FORM_COUNT.times.map { Product.new() } unless self.products.present?
  end

  # 今回更新したい変数は products なので、 products_attributes= という関数を実装している必要があります。
  def products_attributes=(attributes)
    self.products = attributes.map { |_, v| Product.new(v) }
  end

  # エラーがなければ有効と判断する
  def valid?
    super
    # target_productが有効でなければエラーを与える？
    unless target_products.map(&:valid?).all?
      target_products.flat_map { |p| p.errors.full_messages }.uniq.each do |message|
        errors.add(:base, message)
      end
    end
    errors.blank?
  end

  def save
    # valid?で有効と判断されなければ、falseを返す
    return false unless valid?
    # トランザクションで全てがsaveされればtrueとなる
    Product.transaction { target_products.each(&:save!) }
    true
  end

  def target_products
    products.select { |v| ActiveRecord::Type::Boolean.new.cast(v.availability) }
  end

  def check_code_unique
    errors.add(:base, '商品コードが重複しています') if target_products.pluck(:code).count - target_products.pluck(:code).uniq.count > 0
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # 今回の課題には関係ないがつけるのが一般的と考え文字数制限を入れる
  validates :code, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :price,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @form = Form::ProductCollection.new
  end

  def create
    @form = Form::ProductCollection.new(product_collection_params)
    if @form.save
      redirect_to products_path
    else
      render :new
    end

  end

  private

  def product_collection_params
    params.require(:form_product_collection)
          .permit(products_attributes: %i[code name price availability])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>一覧</h1>
<table>
  <thead>
  <tr>
    <th>登録</th>
    <th>商品コード</th>
    <th>商品名</th>
    <th>販売価格</th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.code %></td>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with model: @form, url: products_path, method: :post do |fb| %>
  <%= render 'shared/error_message', object: fb.object %>

  <table class="table">
    <thead>
    <tr>
      <th>登録</th>
      <th>商品コード</th>
      <th>商品名</th>
      <th>販売価格</th>
    </tr>
    </thead>
    <tbody class="bulk-registration-form">
<!--    fields_forはform_with内で渡したモデルとは異なるモデルを編集できるようにするメソッド-->
    <%= fb.fields_for :products do |f| %>
      <tr class="item">
        <td class="text-center">
          <%= f.check_box :availability, class: 'top10 registration-checkbox' %>
        </td>
        <td>
          <%= f.text_field :code, class: 'form-control' %>
        </td>
        <td>
          <%= f.text_field :name, class: 'form-control' %>
        </td>
        <td>
          <%= f.text_field :price, class: 'form-control' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= fb.submit '一括登録', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_messages">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>